### ISSUE TITLE
How to operate json-to-js on single js file or bulk way on top level folder

### ISSUE THREAD

**Issue by ghost** [Dinoshauer/json-to-js#1]
Hi, 
I tried this in terminal:
`json-to-js test.js` it took some time but showed no result nor modification on the file nor any new file created.
I would like some clarification on how to use `pbpaste | json-to-js | pbcopy` too.
Thanks in advance.

**Comment by dinoshauer** [comment]
It sounds like you want to write some javascript to a file?
If it's from the clipboard on a mac, this should work `pbpaste | json-to-js > test.js`

`pbpaste | json-to-js | pbcopy` just takes your clipboard and pipes it into `json-to-js` and then replaces your clipboard with the output
